### ISSUE TITLE
Use NormalFloat instead of Normal for cmp.config.window.bordered()'s winhighlight

### ISSUE THREAD

**Issue by slugbyte** [iguanacucumber/magazine.nvim#3]
### What feature do you feel is missing or should be added

[heres a link to the original issue on nvm-cmp ](https://github.com/hrsh7th/nvim-cmp/issues/2042)

### Description

The winhighlight does not follow the `:help` docs when using the bordered configuration. the help docs recommends pairing `NormalFloat` and `FloatBorder` when configuring floating windows, but nvim-cmp is using `Normal` with `FloatBorder`.

winhighlight is assigned  `Normal:Normal` [here](https://github.com/hrsh7th/nvim-cmp/blob/ae644feb7b67bf1ce4260c231d1d4300b19c6f30/lua/cmp/config/window.lua#L7C1-L7C111)

I was wondering if it could change the borders window winhighlight to 
`NormalFloat:NormalFloat,FloatBorder:FloatBorder,CursorLine:Visual,Search:None`  or  
`Normal:NormalFloat,FloatBorder:FloatBorder,CursorLine:Visual,Search:None`   
In order to make backgrounds and borders consistent with the nvim help docs, other floating windows.

This becomes an issue for colorscheme editors when trying to make nvim-cmps's borders the have the same background color as the main nvim-cmp floating window, it breaks the way borders look for all other floating windows, that follow the `:help` docs. 

### Steps to reproduce

use  `cmp.config.window_bordered()`

``` lua 
cmp.setup({
    window = {
       completion = cmp.config.window.bordered(),
       documentation = cmp.config.window.bordered(),
     },
})
```

### Expected behavior

the winhighlight should use `NormalFloat` for the background when using the bordered config``

### Actual behavior

the winhighlight  uses `Normal` for the background when using the the bordered config

### Additional context

this is what i used for testing my proposed change to winhighlight
 
```lua
cmp.setup({
	window = {
		completion = vim.tbl_extend("force", cmp.config.window.bordered(), {
			winhighlight = "NormalFloat:NormalFloat,FloatBorder:FloatBorder,CursorLine:Visual,Search:None",
		}),
		documentation = vim.tbl_extend("force", cmp.config.window.bordered(), {
			winhighlight = "NormalFloat:NormalFloat,FloatBorder:FloatBorder,CursorLine:Visual,Search:None",
		}),
	},
	-- rest of config
})
```

#### nvims help docs
* `:help hl-NormalFloat` says `"Normal text in floating windows"`
* `:help hl-FloatBorder` says `"Border of floating windows"`

#### related issues
This is an essentially asking for the same thing as issue [nvim-cmp#748](https://github.com/hrsh7th/nvim-cmp/issues/748) (merged in  PR [nvim-cmp#1689](https://github.com/hrsh7th/nvim-cmp/pull/1689)) but for the main window's fg/bg instead of just the border.

I would be happy to create a PR if this is approved :)

**Comment by iguanacucumber** [comment]
You don't need to make a PR, i just made a commit ( with the issue # )
