### ISSUE TITLE
cmp menu above cursor

### ISSUE THREAD

**Issue by insanum** [iguanacucumber/magazine.nvim#4]
### What feature do you feel is missing or should be added

Thanks for putting this repo together and making it available. :-)

There are two PRs on nvim-cmp that deal with having the cmp menu show above the cursor which is useful when using code completion w/ ghost text (i.e., copilot, cody, codeium, etc). Two different approaches and either is useful.

https://github.com/hrsh7th/nvim-cmp/pull/1701
https://github.com/hrsh7th/nvim-cmp/pull/1955

**Comment by iguanacucumber** [comment]
Implemented #1955 & i will implement 1701 soon ( it'll take more time since i need to make 2 PR to not conflict together )

**Comment by iguanacucumber** [comment]
Sorry for taking long to make this (*tbh i just forgot about this issue*) but it's [done](https://github.com/iguanacucumber/magazine.nvim/commit/99d8bd44223de36102305276ee51cbee081cd907) 🎉
