### ISSUE TITLE
plugin is unusable due to `bad argument #2 to 'to_utfindex' (number expected, got string)` errors

### ISSUE THREAD

**Issue by ColinKennedy** [iguanacucumber/magazine.nvim#9]
### documentation & FAQ (at the bottom)

- [X] I have checked the [documentation & FAQ (at the bottom)](https://github.com/iguanacucumber/magazine.nvim/blob/main/doc/cmp.txt) and it didn't resolve my problem.

### Minimal reproducible full config

`~/cmp-repro.lua`
```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    {
        "iguanacucumber/magazine.nvim",
        config = function() require("cmp").setup() end,
    },
  }
})
```

### Description

Neovim Version:
```
:version
NVIM v0.11.0-dev-903+gab98c5b5a
Build type: Debug
LuaJIT 2.1.1727870382
Run ":verbose version" for more info
```

Running on WSL

### Steps to reproduce

Open Neovim with: `nvim -u ~/cmp-repro.lua`

### Expected behavior

The plugin installs and runs as expected

### Actual behavior

lazy.nvim errors on installation with

```
Error detected while processing /home/korinkite/temp/reproduction_magazine_config_issue.lua:
Failed to run `config` for magazine.nvim
.../.repro/data/nvim/lazy/magazine.nvim/lua/cmp/context.lua:56: bad argument #2 to 'to_utfindex' (number expected, got string)
# stacktrace:
  - /magazine.nvim/lua/cmp/context.lua:56 _in_ **new**
  - /magazine.nvim/lua/cmp/context.lua:25 _in_ **empty**
  - /magazine.nvim/lua/cmp/context.lua:44 _in_ **new**
  - /magazine.nvim/lua/cmp/core.lua:28 _in_ **new**
  - /magazine.nvim/lua/cmp/init.lua:12
  - reproduction_magazine_config_issue.lua:8 _in_ **config**
  - reproduction_magazine_config_issue.lua:4
```

And any time I type it also flashes the same message for every character. I have to stop Neovim and disable the plugin to make it stop.

### Additional context

To clarify, the error is specifically on `require("cmp")`. The `require("cmp").setup()` function call doesn't actually have a chance to run. You can verify this by modifying the reproduction to be `config = function() require("cmp") end,` and it will still error

**Comment by iguanacucumber** [comment]
does this happens on a regular 0.10 neovim ?

**Comment by iguanacucumber** [comment]
It seems you're running 0.11 code, with the newer vim.str_utfindex on a older neovim that doesn't have this newer implementation, may you try updating your neovim to the latest nightly release ?
Here's the code causing this issue:
``` lua
misc.to_utfindex = function(text, vimindex) -- called by /magazine.nvim/lua/cmp/context.lua:56
  vimindex = vimindex or #text + 1
  if vim.fn.has('nvim-0.11') == 1 then
    return vim.str_utfindex(text, 'utf-32', math.max(0, math.min(vimindex - 1, #text)))
  else
    return vim.str_utfindex(text, math.max(0, math.min(vimindex - 1, #text)))
  end
end
```

**Comment by ColinKennedy** [comment]
The latest nightly is working. Mine was from October. Thank you! Closing
